from database import db_session

import smtplib, ssl
import yaml
from datetime import datetime
import timeago
from email.message import EmailMessage

with open("config.yml","r") as f:
    config = yaml.load(f, Loader=yaml.SafeLoader)

def send_mail(rcpt, subject, content):
    msg = EmailMessage()
    content = f"{content}\n\n--------\nThis message was auto-generated by the TTN Munich Node Watchdog,\n at {config['general']['base_url']}"
    msg.set_content(content)

    msg['Subject'] = subject
    msg['From'] = config["mail"]["sender"]
    msg['To'] = rcpt

    # Create a secure SSL context
    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(config["mail"]["server"], config["mail"]["port"], context=context) as server:
        server.login(config["mail"]["login"], config["mail"]["password"])
        message = f"Subject: {subject}\n\n{content}"
        server.send_message(msg)

def mail_user_verification(user, token):
    text = f"""Welcome!
Please use this link to validate your email address: {config['general']['base_url']}user/verify/{token.token}
"""
    subject = "TTN Node Watcher - Email Verification"
    send_mail(user.email, subject, text)

def mail_user_login(user, token):
    text = f"""Welcome!
Please use this link to login: {config['general']['base_url']}login/{token.token}
"""
    subject = "TTN Node Watcher - Login"
    send_mail(user.email, subject, text)

def mail_device_offline(device):
    now = datetime.utcnow()
    offline_since = timeago.format(device.last_seen, now)
    text = f"""Your device '{device.dev_id}' from the application '{device.app_id}' has been marked as offline. It was last seen {offline_since}.
"""
    subject = f"TTN Node Watcher - Device {device.dev_id} offline"
    send_mail(device.user.email, subject, text)

def mail_device_online(device):
    now = datetime.utcnow()
    offline_since = timeago.format(device.last_seen, now)
    text = f"""Your device '{device.dev_id}' from the application '{device.app_id}' is back online. It was last seen {offline_since}.
"""
    subject = f"TTN Node Watcher - Device {device.dev_id} back online"
    send_mail(device.user.email, subject, text)
